---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: deployments-repo
  namespace: flux-system
spec:
  secretRef:
    name: flux-system
  interval: 30s
  ref:
    branch: master
  url: ssh://git@github.com/fauzislami/flux-fleet.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deployments
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./cluster/dev-cluster/bblite-deployments
  prune: true
  sourceRef:
    kind: GitRepository
    name: deployments-repo