---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: deployments-repo
  namespace: flux-system
spec:
  secretRef:
    name: flux-system
  interval: 30s
  ref:
    branch: master
  url: ssh://git@github.com/fauzislami/flux-apps-deployment.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: deployments
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./company/blackbox/dev/dev-team-a
  prune: true
  sourceRef:
    kind: GitRepository
    name: deployments-repo