---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: repo-secrets-apple
  namespace: apple
spec:
  interval: 10m0s
  path: ./cluster/dev-cluster/bblite-deployments/tenants/apple/repo
  prune: true
  sourceRef:
    kind: GitRepository
    name: deployments-repo
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-apple
  namespace: apple
spec:
  interval: 1m0s
  path: ./cluster/dev-cluster/bblite-deployments/tenants/apple/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: deployments-repo
    namespace: flux-system
  postBuild:
    substituteFrom: # https://fluxcd.io/docs/components/kustomize/kustomization/#variable-substitution
      - kind: ConfigMap
        name: apple-flux-variables
      - kind: ConfigMap
        name: fruit-version
